
CREATE TABLE Users(
	U_ID			INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	U_Name			VARCHAR(256) NOT NULL,
	U_LoginID		VARCHAR(256) NOT NULL,
	U_Pwd			VARCHAR(256) NOT NULL,
	U_R_ID			INT REFERENCES Roles(R_ID),
	U_CreatedDate	DATETIME DEFAULT GETDATE(),
	U_CreateBy		INT ,
	U_LastLogin		DATETIME,
	U_IsFirstLogin	BIT DEFAULT 1,
	U_UpdateDate	DATETIME NULL,
	U_UpdatedBy		INT
)



CREATE TABLE States(
	S_ID   INT IDENTITY(1,1) PRIMARY KEY,
	S_Name NVARCHAR(256) NOT NULL
)

CREATE TABLE Cities(
	C_ID		INT IDENTITY(1,1) PRIMARY KEY,
	C_Name		NVARCHAR(256) NOT NULL,
	C_StateID	INT REFERENCES States(S_ID)
)



CREATE TABLE Organisations(
	O_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	O_Name VARCHAR(256) NOT NULL,
	O_Address VARCHAR(256) NOT NULL,
	O_CityID INT REFERENCES Cities(C_ID),
	O_StateID INT REFERENCES States(S_ID),
	O_CreatedDate DATETIME DEFAULT GETDATE(),
	O_CreatedBy INT REFERENCES Users(U_ID),
	O_UpdatedDate DATETIME,
	O_UpdatedBy INT REFERENCES Users(U_ID),
)



CREATE TABLE Elections(
	E_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	E_Name VARCHAR(256) NOT NULL,
	E_OrganisationId INT REFERENCES Organisations(O_ID),
	E_ScheduleDate DATETIME NOT NULL,
	E_CreatedDate DATETIME DEFAULT GETDATE(),
	E_CreatedBy INT REFERENCES Users(U_ID),
	E_UpdatedDate DATETIME,
	E_UpdatedBy INT REFERENCES Users(U_ID),
)



CREATE TABLE Positions(
	P_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	P_Name VARCHAR(256) NOT NULL,
	P_ElectionId INT REFERENCES Elections(E_ID),
	P_CreatedDate DATETIME DEFAULT GETDATE(),
	P_CreatedBy INT REFERENCES Users(U_ID),
	P_UpdatedDate DATETIME,
	P_UpdatedBy INT REFERENCES Users(U_ID)
)



CREATE TABLE Candidates
(
	C_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	C_Name VARCHAR(256) NOT NULL,
	C_ElectionId INT REFERENCES Elections(E_ID),
	C_PositionId INT REFERENCES Positions(P_ID),
	C_CreatedDate DATETIME DEFAULT GETDATE(),
	C_CreatedBy INT REFERENCES Users(U_ID),
	C_UpdatedDate DATETIME,
	C_UpdatedBy INT REFERENCES Users(U_ID)
)



CREATE TABLE Voters
(
	V_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	V_Name VARCHAR(256) NOT NULL,
	V_OrganisationId INT REFERENCES Organisations(O_ID),
	V_EmailID VARCHAR(100),
	V_MobileNo VARCHAR(10) NOT NULL,
	V_CreatedDate DATETIME DEFAULT GETDATE(),
	V_CreatedBy INT REFERENCES Users(U_ID),
	V_UpdatedDate DATETIME,
	V_UpdatedBy INT REFERENCES Users(U_ID)
)



CREATE TABLE VoterAuth
(
	VA_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	VA_VoterID INT REFERENCES Voters(V_ID) NOT NULL,
	VA_ElectionId INT REFERENCES Elections(E_ID) NOT NULL,
	VA_LoginId VARCHAR(256) NOT NULL,
	VA_Pwd  VARCHAR(256) NOT NULL,
	VA_IsLoggedIn BIT DEFAULT 0 NOT NULL,
	VA_CreatedDate DATETIME DEFAULT GETDATE(),
	VA_CreatedBy INT REFERENCES Users(U_ID),
	VA_UpdatedDate DATETIME,
	VA_UpdatedBy INT REFERENCES Users(U_ID)
)



CREATE TABLE Outcome
(
	VA_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	VA_VoterID INT REFERENCES Voters(V_ID) NOT NULL,
	VA_ElectionId INT REFERENCES Elections(E_ID) NOT NULL,
	VA_PositionId INT REFERENCES Positions(P_ID) NOT NULL,
	VA_CandidateID INT REFERENCES Candidates(C_ID) NOT NULL,
)

CREATE TABLE SMSLog
(
	SMS_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	SMS_VoterID INT REFERENCES Voters(V_ID) NOT NULL,
	SMS_ElectionId INT REFERENCES Elections(E_ID) NOT NULL,
	SMS_IsSend BIT
)

CREATE TABLE EmailLog
(
	Email_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Email_VoterID INT REFERENCES Voters(V_ID) NOT NULL,
	Email_ElectionId INT REFERENCES Elections(E_ID) NOT NULL,
	Email_IsSend BIT
)

